version: "2"

services:
  django:
    container_name: amlnz
    build: .
    environment:
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
    volumes:
      - ".:/app"
    ports:
      - "8080:8080"
