# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
