# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('campaigns', '0005_campaignrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='campaignrecord',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_records', to='contacts.Contact'),
            preserve_default=False,
        ),
    ]
