# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaignrecord_was_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
