# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='datetime_sent',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
